#pragma once

// typedef enum 
// {
// 	PLATFORM_TYPE_WINDOWS,
// 	PLATFORM_TYPE_LINUX
// }PLATFORM_TYPE;
// 
// 
// #define CURRENT_PLATFORM_TYPE PLATFORM_TYPE_WINDOWS
// //#define CURRENT_PLATFORM_TYPE PLATFORM_TYPE_LINUX

#define USE_PLATFORM_TYPE_LINUX 0
#define USE_PLATFORM_TYPE_WINDOWS 1



